/**
 * 設定 → 実ファイルの中身。`.zshrc` はビルド成果物 (`.next/` をコミットしないのと同じ)。
 * 生成先は $HOME からの相対パス。
 */
import type { ZshConfig } from './config.ts';

export type Generated = Record<string, string>;

/** zsh の alias 値は単一クォート、中の `'` は閉じて繋ぐ */
function quote(value: string): string {
  return `'${value.split("'").join(`'\\''`)}'`;
}

export function generate(config: ZshConfig): Generated {
  const files: Generated = {};

  files['.zshrc'] = `# Generated by \`my apply\`. Edit my/app/_lib/config.ts instead.
# Tool initializations (starship, zoxide, etc.), aliases, and functions are
# split into separate files for readability
[[ -f "$HOME/.zsh/init.zsh" ]] && source "$HOME/.zsh/init.zsh"
[[ -f "$HOME/.zsh/aliases.zsh" ]] && source "$HOME/.zsh/aliases.zsh"
[[ -f "$HOME/.zsh/functions.zsh" ]] && source "$HOME/.zsh/functions.zsh"
`;

  files['.zsh/aliases.zsh'] = `# Generated by \`my apply\`.
${Object.entries(config.aliases)
  .map(([name, command]) => `alias ${quote(name)}=${quote(command)}`)
  .join('\n')}
`;

  // my 自身の配線: 補完の fpath と、cd / source を親シェルに届ける関数。
  // compinit より前に fpath に入っていないと補完が拾われないので、先頭に置く
  files['.zsh/init.zsh'] = `# Generated by \`my apply\`.
# my (decopin-cli): completion and the shell hook for cd / source
path=("$HOME/.local/bin" $path)
fpath=("$HOME/.zsh/completions" $fpath)
if command -v my >/dev/null 2>&1; then
  eval "$(my __shell zsh)"
fi

${config.init.trimEnd()}
`;

  files['.zsh/functions.zsh'] = `# Load every file under ~/.zsh/functions/ (one function per file)
if [[ -d "$HOME/.zsh/functions" ]]; then
  for _zsh_function_file in "$HOME/.zsh/functions"/*.zsh(N); do
    source "$_zsh_function_file"
  done
  unset _zsh_function_file
fi
`;

  for (const [name, body] of Object.entries(config.functions)) {
    files[`.zsh/functions/${name}.zsh`] = body.endsWith('\n') ? body : `${body}\n`;
  }

  return files;
}
